### ISSUE TITLE
Sidekiq::Status::ClientMiddleware has no way to specify expiration

### ISSUE THREAD

**Issue by ivanovv** [utgarda/sidekiq-status#41]
It looks like there is no way to set expiration when queueing a worker
```ruby
def call(worker_class, msg, queue, redis_pool=nil)
      store_status msg['jid'], :queued, nil, redis_pool
      yield
end
```
Third parameter is nil and default expiration ```Sidekiq::Status::DEFAULT_EXPIRY```  will be used.

My use case is: I use one worker that creates several K of subworkers and then waits for them to complete with this code:
```ruby
WORKING_STATUS = [:queued, :working, :failed]
jobs = []
...
smth.each do
  jobs << CustomerImporter.perform_async(connector.id, customer.id)
  ...
end
while jobs.size > 0
  jobs = jobs.select{|job_id| WORKING_STATUS.include? Sidekiq::Status::status(job_id)}
  sleep 10
end
```
About an hour the main worker stops (with several K subworkers in the queue).
Expiration set to 5h:
```ruby
chain.add Sidekiq::Status::ServerMiddleware, expiration: 300.minutes
```

**Comment by topherhunt** [comment]
I believe I'm running into this same issue, can someone confirm that the following is in the same bucket? In my Sidekiq worker I've defined `expiration` thus:

```
  def expiration
    @expiration ||= 60 * 60 * 6 # 6 hours
  end
```

but in the Redis queue I'm seeing indication that status keys are set to expire after 30 minutes:

```
1433183351.762414 [0 127.0.0.1:49224] "expire" "sidekiq:status:d2347b9afde8c47deeaa70eb" "1800"
```

I only figured this out after wasting hours looking elsewhere for the problem, since I had set `expiration: 30.minutes` in the `ServerMiddleware` config but eventually figured out that Sidekiq-Status wasn't respecting this option.
