### ISSUE TITLE
Completed jobs in Sidekiq::Status::Web

### ISSUE THREAD

**Issue by marcboquet** [utgarda/sidekiq-status#44]
I'm moving from resque to sidekiq, and noticed that with `sidekiq-status` I can't see the information for completed jobs as I could with `resque-status`.
So the jobs appear only on the 'Statuses' list when they are being processed, but disappear once they complete, no matter the expiration.
Is this normal behavior or am I doing something wrong?

**Comment by utgarda** [comment]
Yup, it's a feature, at least so far. I can see you started implementing showing completed jobs in your branch?

**Comment by apalancat** [comment]
Yep, have a first implementation but needs a bit more work.
Would you be open to merge it once it's done?

**Comment by utgarda** [comment]
Absolutely. That'd be fabulous. I don' use Sidekiq currently, so I can't point the right direction for new features, all I can do is answer people's questions about how it works, and that's it. And most of the time that's not required, cause the codebase is tiny and ( hopefully ) quite readable. Sharing a feature that is important enough for you to implement is very likely what other users need. Also, it's just a cool thing to do :)

**Comment by vanboom** [comment]
I think this is related to the job not hanging around until expiration...

```ruby
Sidekiq::Status::status( job_id )
```
starts returning `nil` as soon as the job is completed, so I am not able to see that the job has been completed by polling status.

**Comment by pramodshinde** [comment]
@utgarda I drilled down this issue and observed following 

In `Sidekiq::Status::Web` module 
```ruby 
  queue = Sidekiq::Workers.new
```
+ Above API, only return jobs which are in progress i.e. with status `:working` 
+ I also looked into @marcboquet's code on his feature branch but I'm not liking his hack to show up completed jobs on statuses tab.
I started working on this feature at [branch](https://github.com/joshsoftware/sidekiq-status/tree/completed-jobs-on-web) (not committed any code yet).

For this I am thinking of storing some additional info with status for a job instead of using above API.
